/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

import type { Enum, Option } from "./common";

export type U256Input = {
  a: BigNumberish;
  b: BigNumberish;
  c: BigNumberish;
  d: BigNumberish;
};

export type U256Output = { a: BN; b: BN; c: BN; d: BN };

export type AddressInput = { value: string };

export type AddressOutput = { value: string };

export type ContractIdInput = { value: string };

export type ContractIdOutput = { value: string };

export type IdentityInput = Enum<{
  Address: AddressInput;
  ContractId: ContractIdInput;
}>;

export type IdentityOutput = Enum<{
  Address: AddressOutput;
  ContractId: ContractIdOutput;
}>;

interface GovTokenAbiInterface extends Interface {
  functions: {
    decimals: FunctionFragment;
    name: FunctionFragment;
    symbol: FunctionFragment;
    total_supply: FunctionFragment;
    burn: FunctionFragment;
    mint: FunctionFragment;
    owner: FunctionFragment;
    transfer_ownership: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "decimals",
    values?: undefined
  ): Uint8Array;
  encodeFunctionData(functionFragment: "name", values?: undefined): Uint8Array;
  encodeFunctionData(
    functionFragment: "symbol",
    values?: undefined
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "total_supply",
    values?: undefined
  ): Uint8Array;
  encodeFunctionData(functionFragment: "burn", values?: undefined): Uint8Array;
  encodeFunctionData(
    functionFragment: "mint",
    values: [IdentityInput, BigNumberish]
  ): Uint8Array;
  encodeFunctionData(functionFragment: "owner", values?: undefined): Uint8Array;
  encodeFunctionData(
    functionFragment: "transfer_ownership",
    values: [IdentityInput]
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: "decimals",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(functionFragment: "name", data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: "symbol", data: BytesLike): DecodedValue;
  decodeFunctionData(
    functionFragment: "total_supply",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(functionFragment: "burn", data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: "mint", data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: "owner", data: BytesLike): DecodedValue;
  decodeFunctionData(
    functionFragment: "transfer_ownership",
    data: BytesLike
  ): DecodedValue;
}

export class GovTokenAbi extends Contract {
  interface: GovTokenAbiInterface;
  functions: {
    decimals: InvokeFunction<[], number>;

    name: InvokeFunction<[], string>;

    symbol: InvokeFunction<[], string>;

    total_supply: InvokeFunction<[], U256Output>;

    burn: InvokeFunction<[], void>;

    mint: InvokeFunction<
      [recipient: IdentityInput, amount: BigNumberish],
      void
    >;

    owner: InvokeFunction<[], IdentityOutput>;

    transfer_ownership: InvokeFunction<[new_owner: IdentityInput], void>;
  };
}
