/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

interface StableswapHelperContractAbiInterface extends Interface {
  functions: {
    coin_out: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "coin_out",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: "coin_out",
    data: BytesLike
  ): DecodedValue;
}

export class StableswapHelperContractAbi extends Contract {
  interface: StableswapHelperContractAbiInterface;
  functions: {
    coin_out: InvokeFunction<
      [
        coin_in: BigNumberish,
        scale_in: BigNumberish,
        scale_out: BigNumberish,
        reserve_in: BigNumberish,
        reserve_out: BigNumberish
      ],
      BN
    >;
  };
}
