/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type { GovTokenAbi, GovTokenAbiInterface } from "../GovTokenAbi";
const _abi = {
  types: [
    {
      typeId: 0,
      type: "()",
      components: [],
      typeParameters: null,
    },
    {
      typeId: 1,
      type: "b256",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 2,
      type: "enum Errors",
      components: [
        {
          name: "Unauthorized",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 3,
      type: "enum Identity",
      components: [
        {
          name: "Address",
          type: 6,
          typeArguments: null,
        },
        {
          name: "ContractId",
          type: 8,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 4,
      type: "str[32]",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 5,
      type: "str[64]",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 6,
      type: "struct Address",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 7,
      type: "struct BurnedEvent",
      components: [
        {
          name: "amount",
          type: 12,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 8,
      type: "struct ContractId",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 9,
      type: "struct MintedEvent",
      components: [
        {
          name: "recipient",
          type: 3,
          typeArguments: null,
        },
        {
          name: "amount",
          type: 12,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 10,
      type: "struct OwnershipTransferredEvent",
      components: [
        {
          name: "new_owner",
          type: 3,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 11,
      type: "struct U256",
      components: [
        {
          name: "a",
          type: 12,
          typeArguments: null,
        },
        {
          name: "b",
          type: 12,
          typeArguments: null,
        },
        {
          name: "c",
          type: 12,
          typeArguments: null,
        },
        {
          name: "d",
          type: 12,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 12,
      type: "u64",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 13,
      type: "u8",
      components: null,
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [],
      name: "decimals",
      output: {
        name: "",
        type: 13,
        typeArguments: null,
      },
      attributes: null,
    },
    {
      inputs: [],
      name: "name",
      output: {
        name: "",
        type: 5,
        typeArguments: null,
      },
      attributes: null,
    },
    {
      inputs: [],
      name: "symbol",
      output: {
        name: "",
        type: 4,
        typeArguments: null,
      },
      attributes: null,
    },
    {
      inputs: [],
      name: "total_supply",
      output: {
        name: "",
        type: 11,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [],
      name: "burn",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
        {
          name: "payable",
          arguments: [],
        },
      ],
    },
    {
      inputs: [
        {
          name: "recipient",
          type: 3,
          typeArguments: null,
        },
        {
          name: "amount",
          type: 12,
          typeArguments: null,
        },
      ],
      name: "mint",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [],
      name: "owner",
      output: {
        name: "",
        type: 3,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "new_owner",
          type: 3,
          typeArguments: null,
        },
      ],
      name: "transfer_ownership",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
  ],
  loggedTypes: [
    {
      logId: 0,
      loggedType: {
        name: "",
        type: 7,
        typeArguments: [],
      },
    },
    {
      logId: 1,
      loggedType: {
        name: "",
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 2,
      loggedType: {
        name: "",
        type: 9,
        typeArguments: [],
      },
    },
    {
      logId: 3,
      loggedType: {
        name: "",
        type: 2,
        typeArguments: [],
      },
    },
    {
      logId: 4,
      loggedType: {
        name: "",
        type: 10,
        typeArguments: [],
      },
    },
  ],
  messagesTypes: [],
  configurables: [],
};

export class GovTokenAbi__factory {
  static readonly abi = _abi;
  static createInterface(): GovTokenAbiInterface {
    return new Interface(_abi) as unknown as GovTokenAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): GovTokenAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as GovTokenAbi;
  }
}
