/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type {
  StableswapHelperContractAbi,
  StableswapHelperContractAbiInterface,
} from "../StableswapHelperContractAbi";
const _abi = {
  types: [
    {
      typeId: 0,
      type: "u64",
      components: null,
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [
        {
          name: "coin_in",
          type: 0,
          typeArguments: null,
        },
        {
          name: "scale_in",
          type: 0,
          typeArguments: null,
        },
        {
          name: "scale_out",
          type: 0,
          typeArguments: null,
        },
        {
          name: "reserve_in",
          type: 0,
          typeArguments: null,
        },
        {
          name: "reserve_out",
          type: 0,
          typeArguments: null,
        },
      ],
      name: "coin_out",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: null,
    },
  ],
  loggedTypes: [
    {
      logId: 0,
      loggedType: {
        name: "",
        type: 0,
        typeArguments: null,
      },
    },
    {
      logId: 1,
      loggedType: {
        name: "",
        type: 0,
        typeArguments: null,
      },
    },
    {
      logId: 2,
      loggedType: {
        name: "",
        type: 0,
        typeArguments: null,
      },
    },
  ],
  messagesTypes: [],
  configurables: [],
};

export class StableswapHelperContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): StableswapHelperContractAbiInterface {
    return new Interface(
      _abi
    ) as unknown as StableswapHelperContractAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): StableswapHelperContractAbi {
    return new Contract(
      id,
      _abi,
      walletOrProvider
    ) as unknown as StableswapHelperContractAbi;
  }
}
